# Generated by Django 2.1.1 on 2018-11-13 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_type', models.CharField(max_length=30)),
                ('unit_measure', models.CharField(choices=[('kg', 'Kg'), ('par', 'Par'), ('un', 'Unidad'), ('lt', 'Litro')], max_length=10)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TypesDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('unit_measure', models.CharField(choices=[('kg', 'Kg'), ('par', 'Par'), ('un', 'Unidad'), ('lt', 'Litro')], max_length=10)),
                ('quantity_total', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='donation',
            name='accesories',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='clothes',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='shoes',
        ),
        migrations.AddField(
            model_name='detailsdonation',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailsdonation', to='donaciones.Donation'),
        ),
    ]
