# Generated by Django 2.1 on 2019-02-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0002_auto_20190216_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsablefix',
            name='phone',
            field=models.IntegerField(verbose_name='Telefono'),
        ),
    ]
