# Generated by Django 2.1 on 2019-02-18 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0003_auto_20190217_0617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsablefix',
            name='date',
        ),
        migrations.AddField(
            model_name='carry',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creacion'),
        ),
    ]
