# Generated by Django 2.1.1 on 2018-11-14 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0003_auto_20181113_1727'),
        ('donaciones', '0002_auto_20181113_1649'),
    ]

    operations = [
    ]
