# Generated by Django 2.1.1 on 2018-11-19 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0004_merge_20181114_1709'),
        ('donaciones', '0004_merge_20181115_1821'),
    ]

    operations = [
    ]
