# Generated by Django 2.1.1 on 2019-02-27 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0002_auto_20190216_1834'),
        ('donaciones', '0004_auto_20190218_0010'),
    ]

    operations = [
    ]
