# Generated by Django 2.1.1 on 2018-11-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0005_merge_20181120_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypesProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('unit_measure', models.CharField(choices=[('kg', 'Kg'), ('par', 'Par'), ('un', 'Unidad'), ('lt', 'Litro')], max_length=10, verbose_name='Unidad de Medida')),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='detailsdonation',
            name='donation_type',
            field=models.CharField(max_length=30, verbose_name='Tipo de Donación'),
        ),
        migrations.AlterField(
            model_name='detailsdonation',
            name='quantity',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='detailsdonation',
            name='unit_measure',
            field=models.CharField(choices=[('kg', 'Kg'), ('par', 'Par'), ('un', 'Unidad'), ('lt', 'Litro')], max_length=10, verbose_name='Unidad de Medida'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Nombre o Razón Social'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='ticket_number',
            field=models.IntegerField(null=True, verbose_name='Numero de Recibo'),
        ),
        migrations.AlterField(
            model_name='typesdonation',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='typesdonation',
            name='quantity_total',
            field=models.IntegerField(default=0, verbose_name='Cantidad Total'),
        ),
        migrations.AlterField(
            model_name='typesdonation',
            name='unit_measure',
            field=models.CharField(choices=[('kg', 'Kg'), ('par', 'Par'), ('un', 'Unidad'), ('lt', 'Litro')], max_length=10, verbose_name='Unidad de Medida'),
        ),
    ]
