# Generated by Django 2.1 on 2019-03-20 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0005_merge_20190227_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carry',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsable', to='donaciones.ResponsableFix'),
        ),
    ]
