# Generated by Django 2.1.1 on 2018-11-20 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0006_auto_20181120_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('types', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='donaciones.Neighborhood', verbose_name='Tipos de Producto')),
            ],
        ),
    ]
