# Generated by Django 2.1 on 2019-04-28 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0007_auto_20190425_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Numero de telefono'),
        ),
    ]
