# Generated by Django 2.1.1 on 2018-11-21 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0007_sortproducts'),
        ('donaciones', '0005_merge_20181120_1946'),
        ('donaciones', '0005_merge_20181119_2051'),
    ]

    operations = [
    ]
