# Generated by Django 2.1.1 on 2019-08-14 04:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0009_auto_20190814_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typesproducts',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio'),
        ),
    ]
