# Generated by Django 2.1.1 on 2018-11-22 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0009_auto_20181121_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=80, verbose_name='Descripción')),
                ('detailsdonation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='donaciones.DetailsDonation')),
            ],
        ),
    ]
