# Generated by Django 2.1.1 on 2018-11-22 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0009_auto_20181121_0127'),
        ('donaciones', '0008_merge_20181121_0912'),
    ]

    operations = [
    ]
