# Generated by Django 2.1.1 on 2018-11-21 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0010_auto_20181121_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='ref_id',
            new_name='ref',
        ),
    ]
