# Generated by Django 2.1.1 on 2018-11-22 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0011_auto_20181122_1533'),
        ('donaciones', '0012_auto_20181121_1706'),
        ('donaciones', '0010_otherdetail'),
    ]

    operations = [
    ]
