# Generated by Django 2.1.1 on 2018-11-23 21:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0013_merge_20181123_1728'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListSort',
        ),
        migrations.AlterField(
            model_name='detailsdonation',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='ticket_number',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999999)], verbose_name='Numero de Recibo'),
        ),
    ]
