# Generated by Django 2.1.1 on 2018-11-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0014_auto_20181123_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typesdonation',
            name='quantity_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Cantidad Total'),
        ),
    ]
