# Generated by Django 2.1.1 on 2018-11-26 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0016_auto_20181123_1828'),
        ('donaciones', '0013_merge_20181122_1959'),
    ]

    operations = [
    ]
