# Generated by Django 2.1.1 on 2018-11-26 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0013_merge_20181122_1959'),
        ('donaciones', '0016_auto_20181123_1828'),
    ]

    operations = [
    ]
