# Generated by Django 2.1.1 on 2018-11-27 20:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0017_merge_20181127_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ['lastname']},
        ),
        migrations.AlterField(
            model_name='detailsdonation',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nombre del barrio'),
        ),
    ]
