# Generated by Django 2.1.1 on 2018-11-27 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0018_auto_20181126_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_buy', models.DateTimeField(auto_now_add=True)),
                ('familiar', models.CharField(max_length=65, null=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos_familias', to='donaciones.Family')),
            ],
        ),
    ]
