# Generated by Django 2.1.1 on 2018-11-28 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0017_merge_20181127_1923'),
        ('donaciones', '0019_familyentry'),
    ]

    operations = [
    ]
