# Generated by Django 2.1.1 on 2018-11-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0021_auto_20181128_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyentry',
            name='familiar',
        ),
        migrations.AlterField(
            model_name='familyentry',
            name='last_entry',
            field=models.DateField(auto_now_add=True),
        ),
    ]
