# Generated by Django 2.1.1 on 2018-11-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0022_auto_20181128_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referring',
            name='last_buy',
            field=models.DateTimeField(null=True),
        ),
    ]
