# Generated by Django 2.1.1 on 2018-11-29 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0024_auto_20181128_0707'),
        ('donaciones', '0019_typesproducts_quantity_total'),
    ]

    operations = [
    ]
