# Generated by Django 2.1.1 on 2018-11-30 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0019_typesproducts_quantity_total'),
        ('donaciones', '0024_auto_20181128_0707'),
        ('donaciones', '0017_merge_20181126_1955'),
    ]

    operations = [
    ]
