# Generated by Django 2.1.1 on 2018-11-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0025_merge_20181130_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyentry',
            name='familiar',
            field=models.CharField(max_length=65, null=True),
        ),
        migrations.AlterField(
            model_name='familyentry',
            name='last_entry',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
