# Generated by Django 2.1.1 on 2018-11-30 21:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0027_auto_20181130_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortproducts',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MaxValueValidator(99999999.0), django.core.validators.MinValueValidator(0.0)], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='typesproducts',
            name='quantity_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MaxValueValidator(99999999.0), django.core.validators.MinValueValidator(0.0)], verbose_name='Cantidad Total'),
        ),
    ]
