# Generated by Django 2.1.1 on 2018-12-01 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0025_merge_20181129_0636'),
        ('donaciones', '0026_auto_20181130_1757'),
        ('donaciones', '0028_auto_20181130_1851'),
    ]

    operations = [
    ]
