# Generated by Django 2.1.1 on 2018-12-03 19:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0030_fixproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsableFix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=30, verbose_name='Apellido')),
                ('phone', models.IntegerField(default=0)),
                ('adress', models.CharField(max_length=80, verbose_name='Dirección')),
            ],
        ),
        migrations.CreateModel(
            name='TypesFix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('unit_measure', models.CharField(choices=[('kg', 'Kg'), ('par', 'Par'), ('un', 'Unidad'), ('lt', 'Litro')], max_length=10, verbose_name='Unidad de Medida')),
                ('quantity_total', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MaxValueValidator(99999999), django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Total')),
            ],
        ),
        migrations.RemoveField(
            model_name='fixproducts',
            name='name',
        ),
        migrations.RemoveField(
            model_name='fixproducts',
            name='unit_measure',
        ),
        migrations.AddField(
            model_name='fixproducts',
            name='responsable',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='donaciones.ResponsableFix'),
        ),
        migrations.AddField(
            model_name='fixproducts',
            name='types',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='donaciones.TypesFix', verbose_name='Tipos de Producto'),
        ),
    ]
