# Generated by Django 2.1.1 on 2018-12-03 21:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0031_auto_20181203_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsablefix',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MaxValueValidator(99999999.0), django.core.validators.MinValueValidator(0.0)], verbose_name='Cantidad'),
        ),
    ]
