# Generated by Django 2.1.1 on 2018-12-04 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0029_merge_20181129_1203'),
        ('donaciones', '0033_auto_20181203_1904'),
        ('donaciones', '0029_merge_20181130_1916'),
    ]

    operations = [
    ]
