# Generated by Django 2.1.1 on 2018-12-05 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0034_merge_20181204_1004'),
        ('donaciones', '0025_merge_20181130_1543'),
        ('donaciones', '0034_merge_20181203_2055'),
    ]

    operations = [
    ]
