# Generated by Django 2.1.1 on 2018-12-05 04:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0035_merge_20181204_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdetails',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Cantidad'),
        ),
    ]
