# Generated by Django 2.1.1 on 2018-12-05 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0036_auto_20181205_0143'),
        ('donaciones', '0034_merge_20181203_2011'),
    ]

    operations = [
    ]
