# Generated by Django 2.1.1 on 2018-12-06 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0037_merge_20181205_1112'),
        ('donaciones', '0035_merge_20181204_2149'),
        ('donaciones', '0037_merge_20181205_1749'),
    ]

    operations = [
    ]
