# Generated by Django 2.1.1 on 2018-12-06 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0038_merge_20181206_0009'),
        ('donaciones', '0039_responsablefix_state'),
    ]

    operations = [
    ]
