# Generated by Django 2.1.1 on 2018-12-06 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0040_merge_20181206_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='carry',
            name='quantity_back',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Cantidad devolver'),
        ),
    ]
