# Generated by Django 2.1.1 on 2018-12-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0041_carry_quantity_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsablefix',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
