# Generated by Django 2.1.1 on 2018-12-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0043_auto_20181206_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsablefix',
            name='state',
            field=models.BooleanField(default=0),
        ),
    ]
