# Generated by Django 2.1.1 on 2018-12-06 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0038_merge_20181206_1536'),
        ('donaciones', '0044_auto_20181206_1635'),
    ]

    operations = [
    ]
