# Generated by Django 2.1.1 on 2018-12-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0045_merge_20181206_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referring',
            name='last_buy',
            field=models.DateField(null=True),
        ),
    ]
