# Generated by Django 2.1.1 on 2018-12-06 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0045_merge_20181206_2021'),
        ('donaciones', '0046_auto_20181206_1937'),
    ]

    operations = [
    ]
