# Generated by Django 2.1.1 on 2018-12-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0047_merge_20181206_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics', verbose_name='Imagen'),
        ),
    ]
