# Generated by Django 2.1.1 on 2018-12-27 21:41

from django.db import migrations, models
import donaciones.models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0050_auto_20181210_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=donaciones.models.custom_upload_to, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Numero de telefono'),
        ),
    ]
