# Generated by Django 2.1.1 on 2018-12-28 01:48

from django.db import migrations, models
import donaciones.models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0051_auto_20181227_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=donaciones.models.custom_upload_to, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.PositiveIntegerField(verbose_name='Numero de telefono'),
        ),
    ]
